name: share_plus
description: Flutter plugin for sharing content via the platform share UI, using the ACTION_SEND intent on Android and UIActivityViewController on iOS.
version: 4.0.10
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/
publish_to: none

flutter:
  plugin:
    platforms:
      android:
        package: dev.fluttercommunity.plus.share
        pluginClass: SharePlusPlugin
      ios:
        pluginClass: FLTSharePlusPlugin
      linux:
        default_package: share_plus_linux
      macos:
        default_package: share_plus_macos
      web:
        default_package: share_plus_web
      windows:
        default_package: share_plus_windows

dependencies:
  meta: ^1.7.0
  mime: ^1.0.2
  flutter:
    sdk: flutter
  share_plus_platform_interface:
    path: /Users/idan/StudioProjects/plus_plugins/packages/share_plus/share_plus_platform_interface
  share_plus_linux:
    path: /Users/idan/StudioProjects/plus_plugins/packages/share_plus/share_plus_linux
  share_plus_macos:
    path: /Users/idan/StudioProjects/plus_plugins/packages/share_plus/share_plus_macos
  share_plus_windows:
    path: /Users/idan/StudioProjects/plus_plugins/packages/share_plus/share_plus_windows
  share_plus_web:
    path: /Users/idan/StudioProjects/plus_plugins/packages/share_plus/share_plus_web

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"
